# fly.toml app configuration file generated for fairbrix-phantom-wallet-broken-leaf-2937 on 2025-10-19T16:42:18-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fairbrix-phantom-wallet-broken-leaf-2937'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile.swap-backend'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
