# fly.toml app configuration file generated for your-wallet-backend on 2025-10-19T19:39:06-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'your-wallet-backend'
primary_region = 'iad'

[build]
dockerfile = "Dockerfile.wallet"


[[services]]
  internal_port = 9500
  protocol = "tcp"
  [[services.ports]]
    port = 80
    handlers = ["http"]

[[services]]
  internal_port = 9501
  protocol = "tcp"
  [[services.ports]]
    port = 9501
    handlers = ["http"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
